version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=cat_shelter_db
            - MYSQL_USER=cat_shelter
            - MYSQL_PASSWORD=@Haslo1223
            - MYSQL_ROOT_PASSWORD=@Haslo1223
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
